### ISSUE TITLE
Missing manpages in release tarball

### ISSUE THREAD

**Issue by ghost** [kristapsdz/ksql#2]
The ksql 0.2.0 release tarball [1] seems to be missing `ksql_cfg_defaults.3` and `ksql_stmt_step.3`, and doesn't match what's tagged as VERSION_0_2_0 here on GitHub.

`ksql_stmt_step.3` seems to also be missing in older release tarballs.

[1] https://kristaps.bsd.lv/ksql/snapshots/ksql-0.2.0.tar.gz

**Comment by kristapsdz** [comment]
I've added to the tarball and will have this out in 0.2.1---probably tomorrow.  Thanks for the note!
